Pgarza-dev/Noroff-JS-2

- .vscode/settings.json
- index.html
- js/consts.js
- js/services/auth.js
created auth functions for reg users & login users
> create auth. services

- src/index.html
- src/lib/main.js
- src/pages/login/index.html
- src/styles/app.css
> fix merge issues

- vercel.json
updated the outputDirectory to "dist" to fix vercel deployment. Please merge when reviewed :)
> Fix vercel config

- src/lib/page_scripts/signup.js
quick fix to solve vercel issues
> fix imports

- src/components/post/postButtons.html
- src/components/post/postButtons.js
- src/components/post/postReactionsBtn.html
- src/components/post/postReactionsBtns.js
- src/styles/app.css
- adds the ability to add reactions to a post
**Limitations:**
Currently, the reactions are not posted to the API, just stored in the local store.
> feat: add radial reactions menu

- src/components/post/post.html
- src/styles/app.css
style the images for the posts
> style: center post media

- package.json
- pnpm-lock.yaml
- postcss.config.cjs
- src/components/post/post.html
- src/components/post/postComment.html
- src/components/post/postComment.js
- src/components/post/postCommentList.js
- src/components/post/postInputComment.html
- src/components/post/postInputComment.js
- src/styles/app.css
animates the opening and closing of comments with `display: grid` and `fr:0`
> style: animate expanding comment section

- jsconfig.json
- vite.config.js
adds jsconfig.json in order to fix vscode/vite cmd/ctrl click on file paths
> fix Vite aliasing issues

- src/lib/constants.js
- src/lib/forms/validation.js
- src/lib/page_scripts/login.js
- src/lib/page_scripts/signup.js
- src/lib/services/auth.js
- src/lib/services/fetcher.js
- src/lib/services/posts.js
- src/lib/services/types.js
I refactored the services to use a more re-usable fetcher function with some nice optional arguments. This allows our code to be [DRYer](https://docs.getdbt.com/terms/dry#:~:text=DRY%20code%20means%20you%20get,and%20energy%20on%20tedious%20syntax.)
I also moved some more of the consts into the global consts file.
Have a look and tell me what you think :)
> refac fetching and move constants

- src/lib/page_scripts/profile.js
- src/lib/utils/editProfile.js
- src/lib/utils/getUsernameQueryParam.js
- src/pages/profile/index.html
- src/styles/app.css
> edit profile function/get username from querrypram

- src/lib/services/profiles.js
- adds the profile services needed for handling displaying and updating user profiles
> profile service

- src/components/post/postHeader.js
- src/components/post/postInputComment.js
- src/index.html
- src/login/index.html
- src/signup/index.html
- src/user/index.html
- vercel.json
- vite.config.js
restructures the folders for less nesting and cleaners URLs
> restructure folders

- src/lib/page_scripts/login.js
> update login redirect

- src/components/header/header.html
- src/components/post/postHeader.html
- src/components/post/postHeader.js
- src/lib/auth/handleAuth.js
- src/lib/constants.js
- src/lib/main.js
- src/lib/services/auth.js
- src/lib/utils/handleLocalStorageUser.js
- src/login/index.html
- src/signup/index.html
- src/unauthorized/index.html
- vite.config.js
added basic auth check to handle the cases where username or access token is missing from local storage
> add basic auth

- src/components/post/postComment.js
- src/components/post/postInputComment.js
- src/lib/services/posts.js
- adds the ability to comment on a post and reply to other comments
> add commenting feature

- src/components/post-editor/postEditor.html
- src/components/post-editor/postEditor.js
- src/components/post/post.js
- src/components/post/postHeader.html
- src/components/post/postHeader.js
- src/index.html
- src/styles/app.css
- src/user/index.html
- adds the ability to edit a post
- adds the post-editor modal
> feature: add post editing

- src/components/post-reactions/postReactions.html
- src/components/post-reactions/postReactions.js
- src/components/post-reactions/singleReaction.html
- src/components/post-reactions/singleReaction.js
- src/components/post/post.js
- src/components/post/postButtons.js
- src/components/post/postReactionsBtn.html
- src/components/post/postReactionsBtns.js
- src/index.html
- src/lib/services/posts.js
- src/lib/utils/editProfile.js
- src/styles/app.css
Adds the ability to react and view reactions on a post
> add ability to react to posts

- src/components/post-editor/postEditor.html
- src/components/post/post.html
- src/components/post/post.js
- src/components/post/postHeader.html
- src/components/post/postHeader.js
- adds titles to all post and the ability to edit them
> add post titles

- package.json
- pnpm-lock.yaml
- src/components/post/post.html
- src/components/post/postReactionsBtn.html
- src/components/post/postReactionsBtns.js
- src/styles/app.css
- tailwind.config.js
- added animation to update reactions
- added tailwind animate
> add minor animations

- src/index.html
> fix delete btn

- src/components/post/postComment.html
- src/components/post/postComment.js
- src/components/post/postHeader.html
- src/components/post/postHeader.js
- src/lib/page_scripts/feed.js
fixes the broken avatar links in the post and comments
> update post and comment avatar links

- src/components/customComponent.js
- src/components/header/accountMenuDropdown.js
- src/components/header/header.html
- src/components/header/header.js
- src/components/modals/confirmDeleteModal.js
- src/components/post-editor/postEditor.js
- src/components/post-reactions/postReactions.js
- src/components/post-reactions/singleReaction.js
- src/components/post/postButtons.js
- src/components/post/postComment.js
- src/components/post/postCommentList.js
- src/components/post/postHeader.js
- src/components/post/postInputComment.js
- src/components/post/postMedia.js
- src/lib/page_scripts/feed.js
> clean up customComponents class

- src/index.html
- src/lib/page_scripts/user.js
- src/login/index.html
- src/signup/index.html
- src/styles/app.css
- src/user/index.html
- tailwind.config.js
just updated the profile UI and added some minor things. Let me know what you think.
> Profile UI updates

- src/components/modals/confirmDeleteModal.js
- src/components/post/postInputComment.js
- src/components/toast/toast.html
- src/components/toast/toast.js
- src/components/toast/toastWrapper.js
- src/index.html
- src/lib/constants.js
- src/lib/page_scripts/feed.js
- src/lib/page_scripts/settings.js
- src/lib/page_scripts/user.js
- src/lib/services/auth.js
- src/lib/services/fetcher.js
- src/lib/services/makeApiCall.js
- src/lib/services/posts.js
- src/lib/services/profiles.js
- src/lib/stores/toastStore.js
- src/login/index.html
- src/signup/index.html
- src/styles/app.css
- src/user/index.html
This PR serves two main purposes:
Refactored the API calls to make them more DRY and maintainable. A new `makeApiCall` function has been introduced to handle both success and error scenarios in a unified way.
A new Toast notifications feature has been added to enhance the user experience by providing real-time feedback messages. This is integrated with the refactored API calls to handle both success and error messages.
**API Refactoring:** Introduced a makeApiCall function that handles both success and error scenarios.
**Toast Notifications:** Toasts can be of different types: "info", "success", "warning", "error".
Toasts auto-dismiss after a default timeout.
Limit of displaying up to 5 toasts at a time.
**Usage**
To use the Toast feature, you can simply call the addToast method from the …
> Toast & API call wrapper

- src/components/post/post.html
- src/components/post/post.js
- src/lib/page_scripts/post.js
- src/post/index.html
Adds the ability to view a single post by clicking the title of the post
> adds the single post page

- src/index.html
- src/login/index.html
- src/post/index.html
- src/search/index.html
- src/settings/index.html
- src/signup/index.html
- src/unauthorized/index.html
- src/user/index.html
- adds hotjar script for tracking and analytics
> add hotjar tracking

- src/lib/services/posts.js
> fix reactions API call

- src/components/header/header.html
- src/components/post/postReactionsBtns.js
- src/index.html
- src/lib/auth/handleAuth.js
- src/lib/page_scripts/feed.js
- src/lib/utils/getTotalReactionCount.js
- src/lib/utils/sortPosts.js
- src/user/index.html
- adds the final filtering function to the page 🥳🎉
> add filtering for the feed page

- src/lib/auth/handleAuth.js
- src/lib/auth/unauthorized.html
fixes the memory issue caused by the auth
> fix auth redirect

- src/components/toast/toast.js
- src/components/toast/toastWrapper.js
- src/styles/app.css
- updates to toast location to center
> update toast placement

- src/components/post/post.html
- src/components/post/postButtons.html
- src/components/post/postReactionsBtn.html
- src/index.html
- src/login/index.html
- src/signup/index.html
- src/styles/app.css
- src/user/index.html
- make adjustments to the design for a better mobile experience
> tweak design

- src/lib/page_scripts/login.js
- src/lib/page_scripts/signup.js
- src/user/index.html
- vite.config.js
- includes the post page in the build step
> fix post page

- src/components/post/postButtons.html
- src/components/post/postReactionsBtn.html
- src/lib/auth/handleAuth.js
- src/lib/page_scripts/login.js
- src/lib/page_scripts/signup.js
- src/post/index.html
- src/signup/index.html
- src/styles/app.css
- src/user/index.html
- vite.config.js
- removed the `@starting-style` CSS which causes some browsers to crash
> Fix chrome crashing

- src/components/post/post.js
- src/lib/page_scripts/search.js
- src/lib/services/search.js
- src/search/index.html
This PR improves the search functionality by addressing a missing requirement. Users can now search for the title or content of a post, as well as for other users.
> feature: add post content search functionality
